// Event ID lookup tables derived from the Wireshark S7Comm dissector
// (packet-s7comm.c, seemoo-lab/nexmon). Arrays are sorted by key so
// binary_search_by_key gives O(log n) lookup with zero allocations.

// Lookup helper shared by all three tables.
fn lookup(table: &[(u16, &'static str)], id: u16) -> Option<&'static str> {
    table
        .binary_search_by_key(&id, |&(k, _)| k)
        .ok()
        .map(|i| table[i].1)
}

/// Human-readable description of a [`DiagnosticEntry`](crate::DiagnosticEntry) event ID.
///
/// Obtain via [`describe_event`].
pub struct DiagEventInfo {
    /// Event class derived from the high nibble (bits 12–15), e.g. `"Mode transitions"`.
    pub class: &'static str,
    /// Specific event name from the S7 diagnostic tables, or `None` if not catalogued.
    pub name: Option<&'static str>,
}

/// Returns a [`DiagEventInfo`] for the given raw `event_id` from a diagnostic buffer entry.
///
/// Lookup strategy (mirrors the Wireshark S7Comm dissector):
/// - The high nibble (bits 12–15) always identifies the event class.
/// - IDs with class `0x8` or `0x9` are looked up in the standardised diagnostic /
///   predefined-user-event table; all others use the fixed-event table.
///
/// # Example
///
/// ```
/// use rust7::describe_event;
///
/// let info = describe_event(0x4302);
/// assert_eq!(info.class, "Mode transitions");
/// assert_eq!(info.name, Some("Mode transition from STARTUP to RUN"));
/// ```
pub fn describe_event(event_id: u16) -> DiagEventInfo {
    let class_nibble = event_id >> 12;
    let class = lookup(EVENT_CLASS_NAMES, class_nibble).unwrap_or("Unknown");
    let name = if class_nibble == 0x8 || class_nibble == 0x9 {
        lookup(EVENT_0X8_0X9_NAMES, event_id)
    } else {
        lookup(EVENT_FIX_NAMES, event_id)
    };
    DiagEventInfo { class, name }
}

// ── Event class names (high nibble of event_id) ───────────────────────────────

static EVENT_CLASS_NAMES: &[(u16, &str)] = &[
    (0x01, "Standard OB events"),
    (0x02, "Synchronous errors"),
    (0x03, "Asynchronous errors"),
    (0x04, "Mode transitions"),
    (0x05, "Run-time events"),
    (0x06, "Communication events"),
    (0x07, "Events for fail-safe and fault-tolerant systems"),
    (0x08, "Standardized diagnostic data on modules"),
    (0x09, "Predefined user events"),
    (0x0A, "Freely definable events"),
    (0x0B, "Freely definable events"),
    (0x0C, "Reserved"),
    (0x0D, "Reserved"),
    (0x0E, "Reserved"),
    (0x0F, "Events for modules other than CPUs"),
];

// ── Fixed-format event IDs (classes 0x1–0x7, 0xA–0xF) ───────────────────────

static EVENT_FIX_NAMES: &[(u16, &str)] = &[
    (0x113A, "Start request for cyclic interrupt OB with special handling (S7-300 only)"),
    (0x1155, "Status alarm for PROFIBUS DP"),
    (0x1156, "Update interrupt for PROFIBUS DP"),
    (0x1157, "Manufacturer interrupt for PROFIBUS DP"),
    (0x1158, "Status interrupt for PROFINET IO"),
    (0x1159, "Update interrupt for PROFINET IO"),
    (0x115A, "Manufacturer interrupt for PROFINET IO"),
    (0x115B, "IO: Profile-specific interrupt"),
    (0x116A, "Technology synchronization interrupt"),
    (0x1381, "Request for manual warm restart"),
    (0x1382, "Request for automatic warm restart"),
    (0x1383, "Request for manual hot restart"),
    (0x1384, "Request for automatic hot restart"),
    (0x1385, "Request for manual cold restart"),
    (0x1386, "Request for automatic cold restart"),
    (0x1387, "Master CPU: request for manual cold restart"),
    (0x1388, "Master CPU: request for automatic cold restart"),
    (0x138A, "Master CPU: request for manual warm restart"),
    (0x138B, "Master CPU: request for automatic warm restart"),
    (0x138C, "Standby CPU: request for manual hot restart"),
    (0x138D, "Standby CPU: request for automatic hot restart"),
    (0x2521, "BCD conversion error"),
    (0x2522, "Area length error when reading"),
    (0x2523, "Area length error when writing"),
    (0x2524, "Area error when reading"),
    (0x2525, "Area error when writing"),
    (0x2526, "Timer number error"),
    (0x2527, "Counter number error"),
    (0x2528, "Alignment error when reading"),
    (0x2529, "Alignment error when writing"),
    (0x2530, "Write error when accessing the DB"),
    (0x2531, "Write error when accessing the DI"),
    (0x2532, "Block number error when opening a DB"),
    (0x2533, "Block number error when opening a DI"),
    (0x2534, "Block number error when calling an FC"),
    (0x2535, "Block number error when calling an FB"),
    (0x253A, "DB not loaded"),
    (0x253C, "FC not loaded"),
    (0x253D, "SFC not loaded"),
    (0x253E, "FB not loaded"),
    (0x253F, "SFB not loaded"),
    (0x2942, "I/O access error, reading"),
    (0x2943, "I/O access error, writing"),
    (0x3267, "End of module reconfiguration"),
    (0x3367, "Start of module reconfiguration"),
    (0x34A4, "PROFInet Interface DB can be addressed again"),
    (0x3501, "Cycle time exceeded"),
    (0x3502, "User interface (OB or FRB) request error"),
    (0x3503, "Delay too long processing a priority class"),
    (0x3505, "Time-of-day interrupt(s) skipped due to new clock setting"),
    (0x3506, "Time-of-day interrupt(s) skipped when changing to RUN after HOLD"),
    (0x3507, "Multiple OB request errors caused internal buffer overflow"),
    (0x3508, "Synchronous cycle interrupt-timing error"),
    (0x3509, "Interrupt loss due to excess interrupt load"),
    (0x350A, "Resume RUN mode after CiR"),
    (0x350B, "Technology synchronization interrupt - timing error"),
    (0x3571, "Nesting depth too high in nesting levels"),
    (0x3572, "Nesting depth for Master Control Relays too high"),
    (0x3573, "Nesting depth too high after synchronous errors"),
    (0x3574, "Nesting depth for block calls (U stack) too high"),
    (0x3575, "Nesting depth for block calls (B stack) too high"),
    (0x3576, "Local data allocation error"),
    (0x3578, "Unknown instruction"),
    (0x357A, "Jump instruction to target outside of the block"),
    (0x3582, "Memory error detected and corrected by operating system"),
    (0x3583, "Accumulation of detected and corrected memo errors"),
    (0x3585, "Error in the PC operating system (only for LC RTX)"),
    (0x3587, "Multi-bit memory error detected and corrected"),
    (0x35A1, "User interface (OB or FRB) not found"),
    (0x35A2, "OB not loaded (started by SFC or operating system due to configuration)"),
    (0x35A3, "Error when operating system accesses a block"),
    (0x35A4, "PROFInet Interface DB cannot be addressed"),
    (0x35D2, "Diagnostic entries cannot be sent at present"),
    (0x35D3, "Synchronization frames cannot be sent"),
    (0x35D4, "Illegal time jump resulting from synchronization"),
    (0x35D5, "Error adopting the synchronization time"),
    (0x35E1, "Incorrect frame ID in GD"),
    (0x35E2, "GD packet status cannot be entered in DB"),
    (0x35E3, "Frame length error in GD"),
    (0x35E4, "Illegal GD packet number received"),
    (0x35E5, "Error accessing DB in communication SFBs for configured S7 connections"),
    (0x35E6, "GD total status cannot be entered in DB"),
    (0x3821, "BATTF: failure on at least one backup battery of the central rack, problem eliminated"),
    (0x3822, "BAF: failure of backup voltage on central rack, problem eliminated"),
    (0x3823, "24 volt supply failure on central rack, problem eliminated"),
    (0x3825, "BATTF: failure on at least one backup battery of the redundant central rack, problem eliminated"),
    (0x3826, "BAF: failure of backup voltage on redundant central rack, problem eliminated"),
    (0x3827, "24 volt supply failure on redundant central rack, problem eliminated"),
    (0x3831, "BATTF: failure of at least one backup battery of the expansion rack, problem eliminated"),
    (0x3832, "BAF: failure of backup voltage on expansion rack, problem eliminated"),
    (0x3833, "24 volt supply failure on at least one expansion rack, problem eliminated"),
    (0x3842, "Module OK"),
    (0x3854, "PROFINET IO interface submodule/submodule and matches the configured interface submodule/submodule"),
    (0x3855, "PROFINET IO interface submodule/submodule inserted, but does not match the configured interface submodule/submodule"),
    (0x3856, "PROFINET IO interface submodule/submodule inserted, but error in module parameter assignment"),
    (0x3858, "PROFINET IO interface submodule access error corrected"),
    (0x3861, "Module/interface module inserted, module type OK"),
    (0x3863, "Module/interface module plugged in, but wrong module type"),
    (0x3864, "Module/interface module plugged in, but causing problem (type ID unreadable)"),
    (0x3865, "Module plugged in, but error in module parameter assignment"),
    (0x3866, "Module can be addressed again, load voltage error removed"),
    (0x3881, "Interface error leaving state"),
    (0x3884, "Interface module plugged in"),
    (0x38B3, "I/O access error when updating the process image input table"),
    (0x38B4, "I/O access error when transferring the process image to the output modules"),
    (0x38C1, "Expansion rack operational again (1 to 21), leaving state"),
    (0x38C2, "Expansion rack operational again but mismatch between setpoint and actual configuration"),
    (0x38C4, "Distributed I/Os: station failure, leaving state"),
    (0x38C5, "Distributed I/Os: station fault, leaving state"),
    (0x38C6, "Expansion rack operational again, but error(s) in module parameter assignment"),
    (0x38C7, "DP: station operational again, but error(s) in module parameter assignment"),
    (0x38C8, "DP: station operational again, but mismatch between setpoint and actual configuration"),
    (0x38CB, "PROFINET IO station operational again"),
    (0x38CC, "PROFINET IO station error corrected"),
    (0x3921, "BATTF: failure on at least one backup battery of the central rack"),
    (0x3922, "BAF: failure of backup voltage on central rack"),
    (0x3923, "24 volt supply failure on central rack"),
    (0x3925, "BATTF: failure on at least one backup battery of the redundant central rack"),
    (0x3926, "BAF: failure of backup voltage on redundant central rack"),
    (0x3927, "24 volt supply failure on redundant central rack"),
    (0x3931, "BATTF: failure of at least one backup battery of the expansion rack"),
    (0x3932, "BAF: failure of backup voltage on expansion rack"),
    (0x3933, "24 volt supply failure on at least one expansion rack"),
    (0x3942, "Module error"),
    (0x3951, "PROFINET IO submodule removed"),
    (0x3954, "PROFINET IO interface submodule/submodule removed"),
    (0x3961, "Module/interface module removed, cannot be addressed"),
    (0x3966, "Module cannot be addressed, load voltage error"),
    (0x3968, "Module reconfiguration has ended with error"),
    (0x3981, "Interface error entering state"),
    (0x3984, "Interface module removed"),
    (0x3986, "Performance of an H-Sync link negatively affected"),
    (0x39B1, "I/O access error when updating the process image input table"),
    (0x39B2, "I/O access error when transferring the process image to the output modules"),
    (0x39B3, "I/O access error when updating the process image input table"),
    (0x39B4, "I/O access error when transferring the process image to the output modules"),
    (0x39C1, "Expansion rack failure (1 to 21), entering state"),
    (0x39C3, "Distributed I/Os: master system failure entering state"),
    (0x39C4, "Distributed I/Os: station failure, entering state"),
    (0x39C5, "Distributed I/Os: station fault, entering state"),
    (0x39CA, "PROFINET IO system failure"),
    (0x39CB, "PROFINET IO station failure"),
    (0x39CC, "PROFINET IO station error"),
    (0x39CD, "PROFINET IO station operational again, but expected configuration does not match actual configuration"),
    (0x39CE, "PROFINET IO station operational again, but error(s) in module parameter assignment"),
    (0x42F3, "Checksum error detected and corrected by the operating system"),
    (0x42F4, "Standby CPU: connection/update via SFC90 is locked in the master CPU"),
    (0x4300, "Backed-up power on"),
    (0x4301, "Mode transition from STOP to STARTUP"),
    (0x4302, "Mode transition from STARTUP to RUN"),
    (0x4303, "STOP caused by stop switch being activated"),
    (0x4304, "STOP caused by PG STOP operation or by SFB 20 STOP"),
    (0x4305, "HOLD: breakpoint reached"),
    (0x4306, "HOLD: breakpoint exited"),
    (0x4307, "Memory reset started by PG operation"),
    (0x4308, "Memory reset started by switch setting"),
    (0x4309, "Memory reset started automatically (power on not backed up)"),
    (0x430A, "HOLD exited, transition to STOP"),
    (0x430D, "STOP caused by other CPU in multicomputing"),
    (0x430E, "Memory reset executed"),
    (0x430F, "STOP on the module due to STOP on a CPU"),
    (0x4318, "Start of CiR"),
    (0x4319, "CiR completed"),
    (0x4357, "Module watchdog started"),
    (0x4358, "All modules are ready for operation"),
    (0x43B0, "Firmware update was successful"),
    (0x43B4, "Error in firmware fuse"),
    (0x43B6, "Firmware updates canceled by redundant modules"),
    (0x43D3, "STOP on standby CPU"),
    (0x43DC, "Abort during link-up with switchover"),
    (0x43DE, "Updating aborted due to monitoring time being exceeded during the n-th attempt, new update attempt initiated"),
    (0x43DF, "Updating aborted for final time due to monitoring time being exceeded after completing the maximum amount of attempts. User intervention required"),
    (0x43E0, "Change from solo mode after link-up"),
    (0x43E1, "Change from link-up after updating"),
    (0x43E2, "Change from updating to redundant mode"),
    (0x43E3, "Master CPU: change from redundant mode to solo mode"),
    (0x43E4, "Standby CPU: change from redundant mode after error-search mode"),
    (0x43E5, "Standby CPU: change from error-search mode after link-up or STOP"),
    (0x43E6, "Link-up aborted on the standby CPU"),
    (0x43E7, "Updating aborted on the standby CPU"),
    (0x43E8, "Standby CPU: change from link-up after startup"),
    (0x43E9, "Standby CPU: change from startup after updating"),
    (0x43F1, "Reserve-master switchover"),
    (0x43F2, "Coupling of incompatible H-CPUs blocked by system program"),
    (0x4510, "STOP violation of the CPU's data range"),
    (0x4520, "DEFECTIVE: STOP not possible"),
    (0x4521, "DEFECTIVE: failure of instruction processing processor"),
    (0x4522, "DEFECTIVE: failure of clock chip"),
    (0x4523, "DEFECTIVE: failure of clock pulse generator"),
    (0x4524, "DEFECTIVE: failure of timer update function"),
    (0x4525, "DEFECTIVE: failure of multicomputing synchronization"),
    (0x4527, "DEFECTIVE: failure of I/O access monitoring"),
    (0x4528, "DEFECTIVE: failure of scan time monitoring"),
    (0x4530, "DEFECTIVE: memory test error in internal memory"),
    (0x4532, "DEFECTIVE: failure of core resources"),
    (0x4536, "DEFECTIVE: switch defective"),
    (0x4540, "STOP: Memory expansion of the internal work memory has gaps. First memory expansion too small or missing"),
    (0x4541, "STOP caused by priority class system"),
    (0x4542, "STOP caused by object management system"),
    (0x4543, "STOP caused by test functions"),
    (0x4544, "STOP caused by diagnostic system"),
    (0x4545, "STOP caused by communication system"),
    (0x4546, "STOP caused by CPU memory management"),
    (0x4547, "STOP caused by process image management"),
    (0x4548, "STOP caused by I/O management"),
    (0x454A, "STOP caused by configuration: an OB deselected with STEP 7 was being loaded into the CPU during STARTUP"),
    (0x4550, "DEFECTIVE: internal system error"),
    (0x4555, "No restart possible, monitoring time elapsed"),
    (0x4556, "STOP: memory reset request from communication system / due to data inconsistency"),
    (0x4562, "STOP caused by programming error (OB not loaded or not possible)"),
    (0x4563, "STOP caused by I/O access error (OB not loaded or not possible)"),
    (0x4567, "STOP caused by H event"),
    (0x4568, "STOP caused by time error (OB not loaded or not possible)"),
    (0x456A, "STOP caused by diagnostic interrupt (OB not loaded or not possible)"),
    (0x456B, "STOP caused by removing/inserting module (OB not loaded or not possible)"),
    (0x456C, "STOP caused by CPU hardware error (OB not loaded or not possible, or no FRB)"),
    (0x456D, "STOP caused by program sequence error (OB not loaded or not possible)"),
    (0x456E, "STOP caused by communication error (OB not loaded or not possible)"),
    (0x456F, "STOP caused by rack failure OB (OB not loaded or not possible)"),
    (0x4570, "STOP caused by process interrupt (OB not loaded or not possible)"),
    (0x4571, "STOP caused by nesting stack error"),
    (0x4572, "STOP caused by master control relay stack error"),
    (0x4573, "STOP caused by exceeding the nesting depth for synchronous errors"),
    (0x4574, "STOP caused by exceeding interrupt stack nesting depth in the priority class stack"),
    (0x4575, "STOP caused by exceeding block stack nesting depth in the priority class stack"),
    (0x4576, "STOP caused by error when allocating the local data"),
    (0x4578, "STOP caused by unknown opcode"),
    (0x457A, "STOP caused by code length error"),
    (0x457B, "STOP caused by DB not being loaded on on-board I/Os"),
    (0x457D, "Reset/clear request because the version of the internal interface to the integrated technology was changed"),
    (0x457F, "STOP caused by STOP command"),
    (0x4580, "STOP: back-up buffer contents inconsistent (no transition to RUN)"),
    (0x4590, "STOP caused by overloading the internal functions"),
    (0x45D5, "LINK-UP rejected due to mismatched CPU memory configuration of the sub-PLC"),
    (0x45D6, "LINK-UP rejected due to mismatched system program of the sub-PLC"),
    (0x45D8, "DEFECTIVE: hardware fault detected due to other error"),
    (0x45D9, "STOP due to SYNC module error"),
    (0x45DA, "STOP due to synchronization error between H CPUs"),
    (0x45DD, "LINK-UP rejected due to running test or other online functions"),
    (0x4926, "DEFECTIVE: failure of the watchdog for I/O access"),
    (0x4931, "STOP or DEFECTIVE: memory test error in memory submodule"),
    (0x4933, "Checksum error"),
    (0x4934, "DEFECTIVE: memory not available"),
    (0x4935, "DEFECTIVE: cancelled by watchdog/processor exceptions"),
    (0x4949, "STOP caused by continuous hardware interrupt"),
    (0x494D, "STOP caused by I/O error"),
    (0x494E, "STOP caused by power failure"),
    (0x494F, "STOP caused by configuration error"),
    (0x4959, "One or more modules not ready for operation"),
    (0x497C, "STOP caused by integrated technology"),
    (0x49A0, "STOP caused by parameter assignment error or non-permissible variation of setpoint and actual extension: Start-up blocked"),
    (0x49A1, "STOP caused by parameter assignment error: memory reset request"),
    (0x49A2, "STOP caused by error in parameter modification: startup disabled"),
    (0x49A3, "STOP caused by error in parameter modification: memory reset request"),
    (0x49A4, "STOP: inconsistency in configuration data"),
    (0x49A5, "STOP: distributed I/Os: inconsistency in the loaded configuration information"),
    (0x49A6, "STOP: distributed I/Os: invalid configuration information"),
    (0x49A7, "STOP: distributed I/Os: no configuration information"),
    (0x49A8, "STOP: error indicated by the interface module for the distributed I/Os"),
    (0x49B1, "Firmware update data incorrect"),
    (0x49B2, "Firmware update: hardware version does not match firmware"),
    (0x49B3, "Firmware update: module type does not match firmware"),
    (0x49D0, "LINK-UP aborted due to violation of coordination rules"),
    (0x49D1, "LINK-UP/UPDATE sequence aborted"),
    (0x49D2, "Standby CPU changed to STOP due to STOP on the master CPU during link-up"),
    (0x49D4, "STOP on a master, since partner CPU is also a master (link-up error)"),
    (0x49D7, "LINK-UP rejected due to change in user program or in configuration"),
    (0x510F, "A problem as occurred with WinLC. This problem has caused the CPU to go into STOP mode or has caused a fault in the CPU"),
    (0x530D, "New startup information in the STOP mode"),
    (0x5311, "Startup despite Not Ready message from module(s)"),
    (0x5371, "Distributed I/Os: end of the synchronization with a DP master"),
    (0x5380, "Diagnostic buffer entries of interrupt and asynchronous errors disabled"),
    (0x5395, "Distributed I/Os: reset of a DP master"),
    (0x53A2, "Download of technology firmware successful"),
    (0x53A4, "Download of technology DB not successful"),
    (0x53FF, "Reset to factory setting"),
    (0x5445, "Start of System reconfiguration in RUN mode"),
    (0x5481, "All licenses for runtime software are complete again"),
    (0x5498, "No more inconsistency with DP master systems due to CiR"),
    (0x5545, "Start of System reconfiguration in RUN mode"),
    (0x5581, "One or several licenses for runtime software are missing"),
    (0x558A, "Difference between the MLFB of the configured and inserted CPU"),
    (0x558B, "Difference in the firmware version of the configured and inserted CPU"),
    (0x5598, "Start of possible inconsistency with DP master systems due to CiR"),
    (0x55A5, "Version conflict: internal interface with integrated technology"),
    (0x55A6, "The maximum number of technology objects has been exceeded"),
    (0x55A7, "A technology DB of this type is already present"),
    (0x5879, "Diagnostic message from DP interface: EXTF LED off"),
    (0x5960, "Parameter assignment error when switching"),
    (0x5961, "Parameter assignment error"),
    (0x5962, "Parameter assignment error preventing startup"),
    (0x5963, "Parameter assignment error with memory reset request"),
    (0x5966, "Parameter assignment error when switching"),
    (0x5969, "Parameter assignment error with startup blocked"),
    (0x596A, "PROFINET IO: IP address of an IO device already present"),
    (0x596B, "IP address of an Ethernet interface already exists"),
    (0x596C, "Name of an Ethernet interface already exists"),
    (0x596D, "The existing network configuration does not mach the system requirements or configuration"),
    (0x5979, "Diagnostic message from DP interface: EXTF LED on"),
    (0x597C, "DP Global Control command failed or moved"),
    (0x59A0, "The interrupt can not be associated in the CPU"),
    (0x59A1, "Configuration error in the integrated technology"),
    (0x59A3, "Error when downloading the integrated technology"),
    (0x6253, "Firmware update: End of firmware download over the network"),
    (0x6316, "Interface error when starting programmable controller"),
    (0x6353, "Firmware update: Start of firmware download over the network"),
    (0x6390, "Formatting of Micro Memory Card complete"),
    (0x6500, "Connection ID exists twice on module"),
    (0x6501, "Connection resources inadequate"),
    (0x6502, "Error in the connection description"),
    (0x6510, "CFB structure error detected in instance DB when evaluating EPROM"),
    (0x6514, "GD packet number exists twice on the module"),
    (0x6515, "Inconsistent length specifications in GD configuration information"),
    (0x6521, "No memory submodule and no internal memory available"),
    (0x6522, "Illegal memory submodule: replace submodule and reset memory"),
    (0x6523, "Memory reset request due to error accessing submodule"),
    (0x6524, "Memory reset request due to error in block header"),
    (0x6526, "Memory reset request due to memory replacement"),
    (0x6527, "Memory replaced, therefore restart not possible"),
    (0x6528, "Object handling function in the STOP/HOLD mode, no restart possible"),
    (0x652A, "No startup because block exists twice in user memory"),
    (0x652B, "No startup because block is too long for submodule - replace submodule"),
    (0x652C, "No startup due to illegal OB on submodule"),
    (0x6532, "No startup because illegal configuration information on submodule"),
    (0x6533, "Memory reset request because of invalid submodule content"),
    (0x6534, "No startup: block exists more than once on submodule"),
    (0x6535, "No startup: not enough memory to transfer block from submodule"),
    (0x6536, "No startup: submodule contains an illegal block number"),
    (0x6537, "No startup: submodule contains a block with an illegal length"),
    (0x6538, "Local data or write-protection ID (for DB) of a block illegal for CPU"),
    (0x6539, "Illegal command in block (detected by compiler)"),
    (0x653A, "Memory reset request because local OB data on submodule too short"),
    (0x6543, "No startup: illegal block type"),
    (0x6545, "Source language illegal"),
    (0x6546, "Maximum amount of configuration information reached"),
    (0x6547, "Parameter assignment error assigning parameters to modules (not on P bus, cancel download)"),
    (0x6548, "Plausibility error during block check"),
    (0x6549, "Structure error in block"),
    (0x6550, "A block has an error in the CRC"),
    (0x6551, "A block has no CRC"),
    (0x6560, "SCAN overflow"),
    (0x6805, "Resource problem on configured connections, eliminated"),
    (0x6881, "Interface error leaving state"),
    (0x6905, "Resource problem on configured connections"),
    (0x6981, "Interface error entering state"),
    (0x72A2, "Failure of a DP master or a DP master system"),
    (0x72A3, "Redundancy restored on the DP slave"),
    (0x72DB, "Safety program: safety mode disabled"),
    (0x72E0, "Loss of redundancy in communication, problem eliminated"),
    (0x7301, "Loss of redundancy (1 of 2) due to failure of a CPU"),
    (0x7302, "Loss of redundancy (1 of 2) due to STOP on the standby triggered by user"),
    (0x7303, "H system (1 of 2) changed to redundant mode"),
    (0x7323, "Discrepancy found in operating system data"),
    (0x7331, "Standby-master switchover due to master failure"),
    (0x7333, "Standby-master switchover due to system modification during runtime"),
    (0x7334, "Standby-master switchover due to communication error at the synchronization module"),
    (0x7340, "Synchronization error in user program due to elapsed wait time"),
    (0x7341, "Synchronization error in user program due to waiting at different synchronization points"),
    (0x7342, "Synchronization error in operating system due to waiting at different synchronization points"),
    (0x7343, "Synchronization error in operating system due to elapsed wait time"),
    (0x7344, "Synchronization error in operating system due to incorrect data"),
    (0x73A3, "Loss of redundancy on the DP slave"),
    (0x73C1, "Update process canceled"),
    (0x73C2, "Updating aborted due to monitoring time being exceeded during the n-th attempt (1 = n = max. possible number of update attempts after abort due to excessive monitoring time)"),
    (0x73D8, "Safety mode disabled"),
    (0x73DB, "Safety program: safety mode enabled"),
    (0x73E0, "Loss of redundancy in communication"),
    (0x74DD, "Safety program: Shutdown of a fail-save runtime group disabled"),
    (0x74DE, "Safety program: Shutdown of the F program disabled"),
    (0x74DF, "Start of F program initialization"),
    (0x7520, "Error in RAM comparison"),
    (0x7521, "Error in comparison of process image output value"),
    (0x7522, "Error in comparison of memory bits, timers, or counters"),
    (0x75D1, "Safety program: Internal CPU error"),
    (0x75D2, "Safety program error: Cycle time time-out"),
    (0x75D6, "Data corrupted in safety program prior to the output to F I/O"),
    (0x75D7, "Data corrupted in safety program prior to the output to partner F-CPU"),
    (0x75D9, "Invalid REAL number in a DB"),
    (0x75DA, "Safety program: Error in safety data format"),
    (0x75DC, "Runtime group, internal protocol error"),
    (0x75DD, "Safety program: Shutdown of a fail-save runtime group enabled"),
    (0x75DE, "Safety program: Shutdown of the F program enabled"),
    (0x75DF, "End of F program initialization"),
    (0x75E2, "Safety program: Area length error"),
    (0x7852, "SYNC module inserted"),
    (0x7855, "SYNC module eliminated"),
    (0x78D3, "Communication error between PROFIsafe and F I/O"),
    (0x78D4, "Error in safety relevant communication between F CPUs"),
    (0x78D5, "Error in safety relevant communication between F CPUs"),
    (0x78E3, "F-I/O device input channel depassivated"),
    (0x78E4, "F-I/O device output channel depassivated"),
    (0x78E5, "F-I/O device depassivated"),
    (0x7934, "Standby-master switchover due to connection problem at the SYNC module"),
    (0x7950, "Synchronization module missing"),
    (0x7951, "Change at the SYNC module without Power On"),
    (0x7952, "SYNC module removed"),
    (0x7953, "Change at the SYNC-module without reset"),
    (0x7954, "SYNC module: rack number assigned twice"),
    (0x7955, "SYNC module error"),
    (0x7956, "Illegal rack number set on SYNC module"),
    (0x7960, "Redundant I/O: Time-out of discrepancy time at digital input, error is not yet localized"),
    (0x7961, "Redundant I/O, digital input error: Signal change after expiration of the discrepancy time"),
    (0x7962, "Redundant I/O: Digital input error"),
    (0x796F, "Redundant I/O: The I/O was globally disabled"),
    (0x7970, "Redundant I/O: Digital output error"),
    (0x7980, "Redundant I/O: Time-out of discrepancy time at analog input"),
    (0x7981, "Redundant I/O: Analog input error"),
    (0x7990, "Redundant I/O: Analog output error"),
    (0x79D3, "Communication error between PROFIsafe and F I/O"),
    (0x79D4, "Error in safety relevant communication between F CPUs"),
    (0x79D5, "Error in safety relevant communication between F CPUs"),
    (0x79E3, "F-I/O device input channel passivated"),
    (0x79E4, "F-I/O device output channel passivated"),
    (0x79E5, "F-I/O device passivated"),
    (0x79E6, "Inconsistent safety program"),
    (0x79E7, "Simulation block (F system block) loaded"),
];

// ── Standardised diagnostic (0x8xxx) and predefined user (0x9xxx) event IDs ──

static EVENT_0X8_0X9_NAMES: &[(u16, &str)] = &[
    (0x8000, "Module fault/OK"),
    (0x8001, "Internal error"),
    (0x8002, "External error"),
    (0x8003, "Channel error"),
    (0x8004, "No external auxiliary voltage"),
    (0x8005, "No front connector"),
    (0x8006, "No parameter assignment"),
    (0x8007, "Incorrect parameters in module"),
    (0x8030, "User submodule incorrect/not found"),
    (0x8031, "Communication problem"),
    (0x8032, "Operating mode: RUN/STOP (STOP: entering state, RUN: leaving state)"),
    (0x8033, "Time monitoring responded (watchdog)"),
    (0x8034, "Internal module power failure"),
    (0x8035, "BATTF: battery exhausted"),
    (0x8036, "Total backup failed"),
    (0x8040, "Expansion rack failed"),
    (0x8041, "Processor failure"),
    (0x8042, "EPROM error"),
    (0x8043, "RAM error"),
    (0x8044, "ADC/DAC error"),
    (0x8045, "Fuse blown"),
    (0x8046, "Hardware interrupt lost Any"),
    (0x8050, "Configuration/parameter assignment error"),
    (0x8051, "Common mode error"),
    (0x8052, "Short circuit to phase"),
    (0x8053, "Short circuit to ground"),
    (0x8054, "Wire break"),
    (0x8055, "Reference channel error"),
    (0x8056, "Below measuring range"),
    (0x8057, "Above measuring range Analog input"),
    (0x8060, "Configuration/parameter assignment error"),
    (0x8061, "Common mode error"),
    (0x8062, "Short circuit to phase"),
    (0x8063, "Short circuit to ground"),
    (0x8064, "Wire break"),
    (0x8066, "No load voltage"),
    (0x8070, "Configuration/parameter assignment error"),
    (0x8071, "Chassis ground fault"),
    (0x8072, "Short circuit to phase (sensor)"),
    (0x8073, "Short circuit to ground (sensor)"),
    (0x8074, "Wire break"),
    (0x8075, "No sensor power supply Digital input"),
    (0x8080, "Configuration/parameter assignment error"),
    (0x8081, "Chassis ground fault"),
    (0x8082, "Short circuit to phase"),
    (0x8083, "Short circuit to ground"),
    (0x8084, "Wire break"),
    (0x8085, "Fuse tripped"),
    (0x8086, "No load voltage"),
    (0x8087, "Excess temperature Digital output"),
    (0x80B0, "Counter module, signal A faulty"),
    (0x80B1, "Counter module, signal B faulty"),
    (0x80B2, "Counter module, signal N faulty"),
    (0x80B3, "Counter module, incorrect value passed between the channels"),
    (0x80B4, "Counter module, 5.2 V sensor supply faulty"),
    (0x80B5, "Counter module, 24 V sensor supply faulty"),
    (0x9001, "Automatic/Manual mode (coming=man,going=auto)"),
    (0x9002, "OPEN/CLOSED, ON/OFF"),
    (0x9003, "Manual command enable"),
    (0x9004, "Unit protective command (OPEN/CLOSED)"),
    (0x9005, "Process enable"),
    (0x9006, "System protection command"),
    (0x9007, "Process value monitoring responded"),
    (0x9008, "Manipulated variable monitoring responded"),
    (0x9009, "System deviation greater than permitted"),
    (0x900A, "Limit position error"),
    (0x900B, "Runtime error"),
    (0x900C, "Command execution error (sequencer)"),
    (0x900D, "Operating status running > OPEN"),
    (0x900E, "Operating status running > CLOSED"),
    (0x900F, "Command blocking"),
    (0x9011, "Process status OPEN/ON"),
    (0x9012, "Process status CLOSED/OFF"),
    (0x9013, "Process status intermediate position"),
    (0x9014, "Process status ON via AUTO"),
    (0x9015, "Process status ON via manual"),
    (0x9016, "Process status ON via protective command"),
    (0x9017, "Process status OFF via AUTO"),
    (0x9018, "Process status OFF via manual"),
    (0x9019, "Process status OFF via protective command"),
    (0x9021, "Function error on approach"),
    (0x9022, "Function error on leaving"),
    (0x9031, "Actuator (DE/WE) limit position OPEN"),
    (0x9032, "Actuator (DE/WE) limit position not OPEN"),
    (0x9033, "Actuator (DE/WE) limit position CLOSED"),
    (0x9034, "Actuator (DE/WE) limit position not CLOSED"),
    (0x9041, "Illegal status, tolerance time elapsed"),
    (0x9042, "Illegal status, tolerance time not elapsed"),
    (0x9043, "Interlock error, tolerance time = 0"),
    (0x9044, "Interlock error, tolerance time > 0"),
    (0x9045, "No reaction"),
    (0x9046, "Final status exited illegally, tolerance time = 0"),
    (0x9047, "Final status exited illegally, tolerance time > 0"),
    (0x9050, "Upper limit of signal range USR"),
    (0x9051, "Upper limit of measuring range UMR"),
    (0x9052, "Lower limit of signal range LSR"),
    (0x9053, "Lower limit of measuring range LMR"),
    (0x9054, "Upper alarm limit UAL"),
    (0x9055, "Upper warning limit UWL"),
    (0x9056, "Upper tolerance limit UTL"),
    (0x9057, "Lower tolerance limit LTL"),
    (0x9058, "Lower warning limit LWL"),
    (0x9059, "Lower alarm limit LAL"),
    (0x9060, "GRAPH7 step entering/leaving"),
    (0x9061, "GRAPH7 interlock error"),
    (0x9062, "GRAPH7 execution error"),
    (0x9063, "GRAPH7 error noted"),
    (0x9064, "GRAPH7 error acknowledged"),
    (0x9070, "Trend exceeded in positive direction"),
    (0x9071, "Trend exceeded in negative direction"),
    (0x9072, "No reaction"),
    (0x9073, "Final state exited illegally"),
    (0x9080, "Limit value exceeded, tolerance time = 0"),
    (0x9081, "Limit value exceeded, tolerance time > 0"),
    (0x9082, "Below limit value, tolerance time = 0"),
    (0x9083, "Below limit value, tolerance time > 0"),
    (0x9084, "Gradient exceeded, tolerance time = 0"),
    (0x9085, "Gradient exceeded, tolerance time > 0"),
    (0x9086, "Below gradient, tolerance time = 0"),
    (0x9087, "Below gradient, tolerance time > 0"),
    (0x9090, "User parameter assignment error entering/leaving"),
    (0x90F0, "Overflow"),
    (0x90F1, "Underflow"),
    (0x90F2, "Division by 0"),
    (0x90F3, "Illegal calculation operation"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_mode_transition() {
        let info = describe_event(0x4302);
        assert_eq!(info.class, "Mode transitions");
        assert_eq!(info.name, Some("Mode transition from STARTUP to RUN"));
    }

    #[test]
    fn known_module_diagnostic() {
        let info = describe_event(0x8003);
        assert_eq!(info.class, "Standardized diagnostic data on modules");
        assert_eq!(info.name, Some("Channel error"));
    }

    #[test]
    fn known_user_event() {
        let info = describe_event(0x9002);
        assert_eq!(info.class, "Predefined user events");
        assert_eq!(info.name, Some("OPEN/CLOSED, ON/OFF"));
    }

    #[test]
    fn unknown_class_nibble_returns_unknown_class_and_no_name() {
        // High nibble 0x0 is not in the class table.
        let info = describe_event(0x0000);
        assert_eq!(info.class, "Unknown");
        assert!(info.name.is_none());
    }

    #[test]
    fn known_class_but_unlisted_fix_event_returns_none_name() {
        // 0xA000: class "Freely definable events" — no entries in fix table.
        let info = describe_event(0xA000);
        assert_eq!(info.class, "Freely definable events");
        assert!(info.name.is_none());
    }

    #[test]
    fn known_class_but_unlisted_8x_event_returns_none_name() {
        // 0x8010: class "Standardized diagnostic data on modules" but not catalogued.
        let info = describe_event(0x8010);
        assert_eq!(info.class, "Standardized diagnostic data on modules");
        assert!(info.name.is_none());
    }

    #[test]
    fn fix_table_boundary_entries() {
        // First and last entries in EVENT_FIX_NAMES.
        let first = describe_event(0x113A);
        assert_eq!(
            first.name,
            Some("Start request for cyclic interrupt OB with special handling (S7-300 only)")
        );
        let last = describe_event(0x79E7);
        assert_eq!(last.name, Some("Simulation block (F system block) loaded"));
    }

    #[test]
    fn tables_are_sorted() {
        let sorted = |t: &[(u16, &str)]| t.windows(2).all(|w| w[0].0 < w[1].0);
        assert!(sorted(EVENT_CLASS_NAMES), "EVENT_CLASS_NAMES not sorted");
        assert!(sorted(EVENT_FIX_NAMES), "EVENT_FIX_NAMES not sorted");
        assert!(sorted(EVENT_0X8_0X9_NAMES), "EVENT_0X8_0X9_NAMES not sorted");
    }
}
